// flow-typed signature: 50402032e8c6fb7547a1bcde25d867aa
// flow-typed version: <<STUB>>/applicationinsights_v^0.18.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'applicationinsights'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'applicationinsights' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'applicationinsights/applicationinsights' {
  declare module.exports: any;
}

declare module 'applicationinsights/AutoCollection/ClientRequestParser' {
  declare module.exports: any;
}

declare module 'applicationinsights/AutoCollection/ClientRequests' {
  declare module.exports: any;
}

declare module 'applicationinsights/AutoCollection/Console' {
  declare module.exports: any;
}

declare module 'applicationinsights/AutoCollection/Exceptions' {
  declare module.exports: any;
}

declare module 'applicationinsights/AutoCollection/Performance' {
  declare module.exports: any;
}

declare module 'applicationinsights/AutoCollection/RequestDataHelper' {
  declare module.exports: any;
}

declare module 'applicationinsights/AutoCollection/RequestParser' {
  declare module.exports: any;
}

declare module 'applicationinsights/AutoCollection/ServerRequestParser' {
  declare module.exports: any;
}

declare module 'applicationinsights/AutoCollection/ServerRequests' {
  declare module.exports: any;
}

declare module 'applicationinsights/Library/Channel' {
  declare module.exports: any;
}

declare module 'applicationinsights/Library/Client' {
  declare module.exports: any;
}

declare module 'applicationinsights/Library/Config' {
  declare module.exports: any;
}

declare module 'applicationinsights/Library/Context' {
  declare module.exports: any;
}

declare module 'applicationinsights/Library/Contracts' {
  declare module.exports: any;
}

declare module 'applicationinsights/Library/Logging' {
  declare module.exports: any;
}

declare module 'applicationinsights/Library/RequestResponseHeaders' {
  declare module.exports: any;
}

declare module 'applicationinsights/Library/Sender' {
  declare module.exports: any;
}

declare module 'applicationinsights/Library/Util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'applicationinsights/applicationinsights.js' {
  declare module.exports: $Exports<'applicationinsights/applicationinsights'>;
}
declare module 'applicationinsights/AutoCollection/ClientRequestParser.js' {
  declare module.exports: $Exports<'applicationinsights/AutoCollection/ClientRequestParser'>;
}
declare module 'applicationinsights/AutoCollection/ClientRequests.js' {
  declare module.exports: $Exports<'applicationinsights/AutoCollection/ClientRequests'>;
}
declare module 'applicationinsights/AutoCollection/Console.js' {
  declare module.exports: $Exports<'applicationinsights/AutoCollection/Console'>;
}
declare module 'applicationinsights/AutoCollection/Exceptions.js' {
  declare module.exports: $Exports<'applicationinsights/AutoCollection/Exceptions'>;
}
declare module 'applicationinsights/AutoCollection/Performance.js' {
  declare module.exports: $Exports<'applicationinsights/AutoCollection/Performance'>;
}
declare module 'applicationinsights/AutoCollection/RequestDataHelper.js' {
  declare module.exports: $Exports<'applicationinsights/AutoCollection/RequestDataHelper'>;
}
declare module 'applicationinsights/AutoCollection/RequestParser.js' {
  declare module.exports: $Exports<'applicationinsights/AutoCollection/RequestParser'>;
}
declare module 'applicationinsights/AutoCollection/ServerRequestParser.js' {
  declare module.exports: $Exports<'applicationinsights/AutoCollection/ServerRequestParser'>;
}
declare module 'applicationinsights/AutoCollection/ServerRequests.js' {
  declare module.exports: $Exports<'applicationinsights/AutoCollection/ServerRequests'>;
}
declare module 'applicationinsights/Library/Channel.js' {
  declare module.exports: $Exports<'applicationinsights/Library/Channel'>;
}
declare module 'applicationinsights/Library/Client.js' {
  declare module.exports: $Exports<'applicationinsights/Library/Client'>;
}
declare module 'applicationinsights/Library/Config.js' {
  declare module.exports: $Exports<'applicationinsights/Library/Config'>;
}
declare module 'applicationinsights/Library/Context.js' {
  declare module.exports: $Exports<'applicationinsights/Library/Context'>;
}
declare module 'applicationinsights/Library/Contracts.js' {
  declare module.exports: $Exports<'applicationinsights/Library/Contracts'>;
}
declare module 'applicationinsights/Library/Logging.js' {
  declare module.exports: $Exports<'applicationinsights/Library/Logging'>;
}
declare module 'applicationinsights/Library/RequestResponseHeaders.js' {
  declare module.exports: $Exports<'applicationinsights/Library/RequestResponseHeaders'>;
}
declare module 'applicationinsights/Library/Sender.js' {
  declare module.exports: $Exports<'applicationinsights/Library/Sender'>;
}
declare module 'applicationinsights/Library/Util.js' {
  declare module.exports: $Exports<'applicationinsights/Library/Util'>;
}
