// flow-typed signature: 9aebe007a39abaf4ab575d5b8d54b3d0
// flow-typed version: <<STUB>>/babel-messages_v^6.23.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-messages'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-messages' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-messages/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-messages/lib/index.js' {
  declare module.exports: $Exports<'babel-messages/lib/index'>;
}
