// flow-typed signature: ff7df696da1e0cd98fd753d0143fb119
// flow-typed version: <<STUB>>/function-bind_v^1.1.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'function-bind'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'function-bind' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'function-bind/implementation' {
  declare module.exports: any;
}

declare module 'function-bind/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'function-bind/implementation.js' {
  declare module.exports: $Exports<'function-bind/implementation'>;
}
declare module 'function-bind/index' {
  declare module.exports: $Exports<'function-bind'>;
}
declare module 'function-bind/index.js' {
  declare module.exports: $Exports<'function-bind'>;
}
declare module 'function-bind/test/index.js' {
  declare module.exports: $Exports<'function-bind/test/index'>;
}
