// flow-typed signature: 352e137b60c50aff7c643d282f7063a2
// flow-typed version: <<STUB>>/inject-loader_v^2.0.1/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'inject-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'inject-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'inject-loader/index' {
  declare module.exports: $Exports<'inject-loader'>;
}
declare module 'inject-loader/index.js' {
  declare module.exports: $Exports<'inject-loader'>;
}
