// flow-typed signature: 69dc25714f1aa4c0c392551811c3d42e
// flow-typed version: <<STUB>>/karma-sinon-as-promised_v^0.1.6/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-sinon-as-promised'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-sinon-as-promised' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'karma-sinon-as-promised/index' {
  declare module.exports: $Exports<'karma-sinon-as-promised'>;
}
declare module 'karma-sinon-as-promised/index.js' {
  declare module.exports: $Exports<'karma-sinon-as-promised'>;
}
