// flow-typed signature: 8c193e7f1d2dba991f56367894a150d2
// flow-typed version: <<STUB>>/karma-chai_v^0.1.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-chai'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-chai' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karma-chai/adapter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karma-chai/adapter.js' {
  declare module.exports: $Exports<'karma-chai/adapter'>;
}
declare module 'karma-chai/index' {
  declare module.exports: $Exports<'karma-chai'>;
}
declare module 'karma-chai/index.js' {
  declare module.exports: $Exports<'karma-chai'>;
}
