// flow-typed signature: 218588f8d6e129fef57b83f3f125bccc
// flow-typed version: <<STUB>>/karma-chai-as-promised_v^0.1.2/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-chai-as-promised'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-chai-as-promised' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'karma-chai-as-promised/index' {
  declare module.exports: $Exports<'karma-chai-as-promised'>;
}
declare module 'karma-chai-as-promised/index.js' {
  declare module.exports: $Exports<'karma-chai-as-promised'>;
}
