// flow-typed signature: dc98a204a77c3c5ca1fd79c0e36df259
// flow-typed version: <<STUB>>/lodash-inflection_v^1.5.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash-inflection'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash-inflection' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lodash-inflection/gulpfile' {
  declare module.exports: any;
}

declare module 'lodash-inflection/lib/lodash-inflection' {
  declare module.exports: any;
}

declare module 'lodash-inflection/test/gsub' {
  declare module.exports: any;
}

declare module 'lodash-inflection/test/inflector' {
  declare module.exports: any;
}

declare module 'lodash-inflection/test/irregular' {
  declare module.exports: any;
}

declare module 'lodash-inflection/test/ordinalize' {
  declare module.exports: any;
}

declare module 'lodash-inflection/test/plural' {
  declare module.exports: any;
}

declare module 'lodash-inflection/test/pluralize' {
  declare module.exports: any;
}

declare module 'lodash-inflection/test/setup' {
  declare module.exports: any;
}

declare module 'lodash-inflection/test/singular' {
  declare module.exports: any;
}

declare module 'lodash-inflection/test/singularize' {
  declare module.exports: any;
}

declare module 'lodash-inflection/test/titleize' {
  declare module.exports: any;
}

declare module 'lodash-inflection/test/uncountable' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lodash-inflection/gulpfile.js' {
  declare module.exports: $Exports<'lodash-inflection/gulpfile'>;
}
declare module 'lodash-inflection/index' {
  declare module.exports: $Exports<'lodash-inflection'>;
}
declare module 'lodash-inflection/index.js' {
  declare module.exports: $Exports<'lodash-inflection'>;
}
declare module 'lodash-inflection/lib/lodash-inflection.js' {
  declare module.exports: $Exports<'lodash-inflection/lib/lodash-inflection'>;
}
declare module 'lodash-inflection/test/gsub.js' {
  declare module.exports: $Exports<'lodash-inflection/test/gsub'>;
}
declare module 'lodash-inflection/test/inflector.js' {
  declare module.exports: $Exports<'lodash-inflection/test/inflector'>;
}
declare module 'lodash-inflection/test/irregular.js' {
  declare module.exports: $Exports<'lodash-inflection/test/irregular'>;
}
declare module 'lodash-inflection/test/ordinalize.js' {
  declare module.exports: $Exports<'lodash-inflection/test/ordinalize'>;
}
declare module 'lodash-inflection/test/plural.js' {
  declare module.exports: $Exports<'lodash-inflection/test/plural'>;
}
declare module 'lodash-inflection/test/pluralize.js' {
  declare module.exports: $Exports<'lodash-inflection/test/pluralize'>;
}
declare module 'lodash-inflection/test/setup.js' {
  declare module.exports: $Exports<'lodash-inflection/test/setup'>;
}
declare module 'lodash-inflection/test/singular.js' {
  declare module.exports: $Exports<'lodash-inflection/test/singular'>;
}
declare module 'lodash-inflection/test/singularize.js' {
  declare module.exports: $Exports<'lodash-inflection/test/singularize'>;
}
declare module 'lodash-inflection/test/titleize.js' {
  declare module.exports: $Exports<'lodash-inflection/test/titleize'>;
}
declare module 'lodash-inflection/test/uncountable.js' {
  declare module.exports: $Exports<'lodash-inflection/test/uncountable'>;
}
