// flow-typed signature: f0093ec44c8363f8fee448ab23d30c9a
// flow-typed version: <<STUB>>/loglevel_v^1.4.1/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'loglevel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'loglevel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'loglevel/dist/loglevel' {
  declare module.exports: any;
}

declare module 'loglevel/dist/loglevel.min' {
  declare module.exports: any;
}

declare module 'loglevel/Gruntfile' {
  declare module.exports: any;
}

declare module 'loglevel/lib/loglevel' {
  declare module.exports: any;
}

declare module 'loglevel/test/console-fallback-test' {
  declare module.exports: any;
}

declare module 'loglevel/test/cookie-test' {
  declare module.exports: any;
}

declare module 'loglevel/test/default-level-test' {
  declare module.exports: any;
}

declare module 'loglevel/test/get-current-level-test' {
  declare module.exports: any;
}

declare module 'loglevel/test/global-integration-with-new-context' {
  declare module.exports: any;
}

declare module 'loglevel/test/global-integration' {
  declare module.exports: any;
}

declare module 'loglevel/test/integration-smoke-test' {
  declare module.exports: any;
}

declare module 'loglevel/test/level-setting-test' {
  declare module.exports: any;
}

declare module 'loglevel/test/local-storage-test' {
  declare module.exports: any;
}

declare module 'loglevel/test/method-factory-test' {
  declare module.exports: any;
}

declare module 'loglevel/test/multiple-logger-test' {
  declare module.exports: any;
}

declare module 'loglevel/test/node-integration' {
  declare module.exports: any;
}

declare module 'loglevel/test/test-context-using-apply' {
  declare module.exports: any;
}

declare module 'loglevel/test/test-helpers' {
  declare module.exports: any;
}

declare module 'loglevel/test/test-qunit' {
  declare module.exports: any;
}

declare module 'loglevel/test/vendor/json2' {
  declare module.exports: any;
}

// Filename aliases
declare module 'loglevel/dist/loglevel.js' {
  declare module.exports: $Exports<'loglevel/dist/loglevel'>;
}
declare module 'loglevel/dist/loglevel.min.js' {
  declare module.exports: $Exports<'loglevel/dist/loglevel.min'>;
}
declare module 'loglevel/Gruntfile.js' {
  declare module.exports: $Exports<'loglevel/Gruntfile'>;
}
declare module 'loglevel/lib/loglevel.js' {
  declare module.exports: $Exports<'loglevel/lib/loglevel'>;
}
declare module 'loglevel/test/console-fallback-test.js' {
  declare module.exports: $Exports<'loglevel/test/console-fallback-test'>;
}
declare module 'loglevel/test/cookie-test.js' {
  declare module.exports: $Exports<'loglevel/test/cookie-test'>;
}
declare module 'loglevel/test/default-level-test.js' {
  declare module.exports: $Exports<'loglevel/test/default-level-test'>;
}
declare module 'loglevel/test/get-current-level-test.js' {
  declare module.exports: $Exports<'loglevel/test/get-current-level-test'>;
}
declare module 'loglevel/test/global-integration-with-new-context.js' {
  declare module.exports: $Exports<'loglevel/test/global-integration-with-new-context'>;
}
declare module 'loglevel/test/global-integration.js' {
  declare module.exports: $Exports<'loglevel/test/global-integration'>;
}
declare module 'loglevel/test/integration-smoke-test.js' {
  declare module.exports: $Exports<'loglevel/test/integration-smoke-test'>;
}
declare module 'loglevel/test/level-setting-test.js' {
  declare module.exports: $Exports<'loglevel/test/level-setting-test'>;
}
declare module 'loglevel/test/local-storage-test.js' {
  declare module.exports: $Exports<'loglevel/test/local-storage-test'>;
}
declare module 'loglevel/test/method-factory-test.js' {
  declare module.exports: $Exports<'loglevel/test/method-factory-test'>;
}
declare module 'loglevel/test/multiple-logger-test.js' {
  declare module.exports: $Exports<'loglevel/test/multiple-logger-test'>;
}
declare module 'loglevel/test/node-integration.js' {
  declare module.exports: $Exports<'loglevel/test/node-integration'>;
}
declare module 'loglevel/test/test-context-using-apply.js' {
  declare module.exports: $Exports<'loglevel/test/test-context-using-apply'>;
}
declare module 'loglevel/test/test-helpers.js' {
  declare module.exports: $Exports<'loglevel/test/test-helpers'>;
}
declare module 'loglevel/test/test-qunit.js' {
  declare module.exports: $Exports<'loglevel/test/test-qunit'>;
}
declare module 'loglevel/test/vendor/json2.js' {
  declare module.exports: $Exports<'loglevel/test/vendor/json2'>;
}
