// flow-typed signature: 0bf23cbf440ab5db171de5bea0ad662c
// flow-typed version: <<STUB>>/pace-progress_v^1.0.2/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pace-progress'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'pace-progress' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pace-progress/docs/lib/color' {
  declare module.exports: any;
}

declare module 'pace-progress/docs/lib/themes' {
  declare module.exports: any;
}

declare module 'pace-progress/pace' {
  declare module.exports: any;
}

declare module 'pace-progress/pace.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pace-progress/docs/lib/color.js' {
  declare module.exports: $Exports<'pace-progress/docs/lib/color'>;
}
declare module 'pace-progress/docs/lib/themes.js' {
  declare module.exports: $Exports<'pace-progress/docs/lib/themes'>;
}
declare module 'pace-progress/pace.js' {
  declare module.exports: $Exports<'pace-progress/pace'>;
}
declare module 'pace-progress/pace.min.js' {
  declare module.exports: $Exports<'pace-progress/pace.min'>;
}
