// flow-typed signature: 51b3581b1b5ef0e91b10f7dbd7acaae1
// flow-typed version: <<STUB>>/pace_v0.0.4/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pace'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'pace' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pace/pace' {
  declare module.exports: any;
}

declare module 'pace/test/advanced' {
  declare module.exports: any;
}

declare module 'pace/test/simple' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pace/pace.js' {
  declare module.exports: $Exports<'pace/pace'>;
}
declare module 'pace/test/advanced.js' {
  declare module.exports: $Exports<'pace/test/advanced'>;
}
declare module 'pace/test/simple.js' {
  declare module.exports: $Exports<'pace/test/simple'>;
}
