// flow-typed signature: 625b6317336c4999e8f5004df257bbdf
// flow-typed version: <<STUB>>/vee-validate_v^2.0.0-beta.21/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vee-validate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'vee-validate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vee-validate/build/rollup.config' {
  declare module.exports: any;
}

declare module 'vee-validate/build/rollup.es2015.config' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/ar' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/da' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/de' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/el' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/en' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/es' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/fa' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/fi' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/fr' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/he' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/id' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/it' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/ja' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/ka' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/ko' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/nl' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/no' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/pl' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/pt_BR' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/ru' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/sv' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/tr' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/vi' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/zh_CN' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/vee-validate.es2015' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/vee-validate' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/vee-validate.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vee-validate/build/rollup.config.js' {
  declare module.exports: $Exports<'vee-validate/build/rollup.config'>;
}
declare module 'vee-validate/build/rollup.es2015.config.js' {
  declare module.exports: $Exports<'vee-validate/build/rollup.es2015.config'>;
}
declare module 'vee-validate/dist/locale/ar.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/ar'>;
}
declare module 'vee-validate/dist/locale/da.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/da'>;
}
declare module 'vee-validate/dist/locale/de.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/de'>;
}
declare module 'vee-validate/dist/locale/el.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/el'>;
}
declare module 'vee-validate/dist/locale/en.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/en'>;
}
declare module 'vee-validate/dist/locale/es.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/es'>;
}
declare module 'vee-validate/dist/locale/fa.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/fa'>;
}
declare module 'vee-validate/dist/locale/fi.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/fi'>;
}
declare module 'vee-validate/dist/locale/fr.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/fr'>;
}
declare module 'vee-validate/dist/locale/he.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/he'>;
}
declare module 'vee-validate/dist/locale/id.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/id'>;
}
declare module 'vee-validate/dist/locale/it.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/it'>;
}
declare module 'vee-validate/dist/locale/ja.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/ja'>;
}
declare module 'vee-validate/dist/locale/ka.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/ka'>;
}
declare module 'vee-validate/dist/locale/ko.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/ko'>;
}
declare module 'vee-validate/dist/locale/nl.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/nl'>;
}
declare module 'vee-validate/dist/locale/no.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/no'>;
}
declare module 'vee-validate/dist/locale/pl.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/pl'>;
}
declare module 'vee-validate/dist/locale/pt_BR.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/pt_BR'>;
}
declare module 'vee-validate/dist/locale/ru.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/ru'>;
}
declare module 'vee-validate/dist/locale/sv.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/sv'>;
}
declare module 'vee-validate/dist/locale/tr.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/tr'>;
}
declare module 'vee-validate/dist/locale/vi.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/vi'>;
}
declare module 'vee-validate/dist/locale/zh_CN.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/zh_CN'>;
}
declare module 'vee-validate/dist/vee-validate.es2015.js' {
  declare module.exports: $Exports<'vee-validate/dist/vee-validate.es2015'>;
}
declare module 'vee-validate/dist/vee-validate.js' {
  declare module.exports: $Exports<'vee-validate/dist/vee-validate'>;
}
declare module 'vee-validate/dist/vee-validate.min.js' {
  declare module.exports: $Exports<'vee-validate/dist/vee-validate.min'>;
}
