// flow-typed signature: 0df19029a366f62d4ca0697e8b057963
// flow-typed version: <<STUB>>/vue-focus_v^2.1.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-focus'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-focus' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-focus/dist/vue-focus.common' {
  declare module.exports: any;
}

declare module 'vue-focus/dist/vue-focus' {
  declare module.exports: any;
}

declare module 'vue-focus/dist/vue-focus.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-focus/dist/vue-focus.common.js' {
  declare module.exports: $Exports<'vue-focus/dist/vue-focus.common'>;
}
declare module 'vue-focus/dist/vue-focus.js' {
  declare module.exports: $Exports<'vue-focus/dist/vue-focus'>;
}
declare module 'vue-focus/dist/vue-focus.min.js' {
  declare module.exports: $Exports<'vue-focus/dist/vue-focus.min'>;
}
declare module 'vue-focus/index' {
  declare module.exports: $Exports<'vue-focus'>;
}
declare module 'vue-focus/index.js' {
  declare module.exports: $Exports<'vue-focus'>;
}
