// flow-typed signature: 044863d3bd0842fd19d01fd2d3668d38
// flow-typed version: <<STUB>>/vue-chartjs_v^2.3.2/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-chartjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-chartjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-chartjs/build/build' {
  declare module.exports: any;
}

declare module 'vue-chartjs/build/dev-client' {
  declare module.exports: any;
}

declare module 'vue-chartjs/build/dev-server' {
  declare module.exports: any;
}

declare module 'vue-chartjs/build/utils' {
  declare module.exports: any;
}

declare module 'vue-chartjs/build/webpack.base.conf' {
  declare module.exports: any;
}

declare module 'vue-chartjs/build/webpack.dev.conf' {
  declare module.exports: any;
}

declare module 'vue-chartjs/build/webpack.prod.conf' {
  declare module.exports: any;
}

declare module 'vue-chartjs/build/webpack.release' {
  declare module.exports: any;
}

declare module 'vue-chartjs/config/dev.env' {
  declare module.exports: any;
}

declare module 'vue-chartjs/config/index' {
  declare module.exports: any;
}

declare module 'vue-chartjs/config/prod.env' {
  declare module.exports: any;
}

declare module 'vue-chartjs/config/test.env' {
  declare module.exports: any;
}

declare module 'vue-chartjs/dist/vue-chartjs' {
  declare module.exports: any;
}

declare module 'vue-chartjs/docs/dist/vue-chartjs' {
  declare module.exports: any;
}

declare module 'vue-chartjs/src/BaseCharts/Bar' {
  declare module.exports: any;
}

declare module 'vue-chartjs/src/BaseCharts/Bubble' {
  declare module.exports: any;
}

declare module 'vue-chartjs/src/BaseCharts/Doughnut' {
  declare module.exports: any;
}

declare module 'vue-chartjs/src/BaseCharts/Line' {
  declare module.exports: any;
}

declare module 'vue-chartjs/src/BaseCharts/Pie' {
  declare module.exports: any;
}

declare module 'vue-chartjs/src/BaseCharts/PolarArea' {
  declare module.exports: any;
}

declare module 'vue-chartjs/src/BaseCharts/Radar' {
  declare module.exports: any;
}

declare module 'vue-chartjs/src/examples/BarExample' {
  declare module.exports: any;
}

declare module 'vue-chartjs/src/examples/BubbleExample' {
  declare module.exports: any;
}

declare module 'vue-chartjs/src/examples/DoughnutExample' {
  declare module.exports: any;
}

declare module 'vue-chartjs/src/examples/LineExample' {
  declare module.exports: any;
}

declare module 'vue-chartjs/src/examples/PieExample' {
  declare module.exports: any;
}

declare module 'vue-chartjs/src/examples/PolarAreaExample' {
  declare module.exports: any;
}

declare module 'vue-chartjs/src/examples/RadarExample' {
  declare module.exports: any;
}

declare module 'vue-chartjs/src/examples/ReactiveExample' {
  declare module.exports: any;
}

declare module 'vue-chartjs/src/examples/ReactivePropExample' {
  declare module.exports: any;
}

declare module 'vue-chartjs/src/helpers/options' {
  declare module.exports: any;
}

declare module 'vue-chartjs/src/index' {
  declare module.exports: any;
}

declare module 'vue-chartjs/src/mixins/index' {
  declare module.exports: any;
}

declare module 'vue-chartjs/src/mixins/reactiveData' {
  declare module.exports: any;
}

declare module 'vue-chartjs/src/mixins/reactiveProp' {
  declare module.exports: any;
}

declare module 'vue-chartjs/test/e2e/custom-assertions/elementCount' {
  declare module.exports: any;
}

declare module 'vue-chartjs/test/e2e/nightwatch.conf' {
  declare module.exports: any;
}

declare module 'vue-chartjs/test/e2e/runner' {
  declare module.exports: any;
}

declare module 'vue-chartjs/test/e2e/specs/test' {
  declare module.exports: any;
}

declare module 'vue-chartjs/test/unit/index' {
  declare module.exports: any;
}

declare module 'vue-chartjs/test/unit/karma.conf' {
  declare module.exports: any;
}

declare module 'vue-chartjs/test/unit/specs/Bar.spec' {
  declare module.exports: any;
}

declare module 'vue-chartjs/test/unit/specs/Bubble.spec' {
  declare module.exports: any;
}

declare module 'vue-chartjs/test/unit/specs/Doughnut.spec' {
  declare module.exports: any;
}

declare module 'vue-chartjs/test/unit/specs/helpers/options.spec' {
  declare module.exports: any;
}

declare module 'vue-chartjs/test/unit/specs/Line.spec' {
  declare module.exports: any;
}

declare module 'vue-chartjs/test/unit/specs/mixins/reactiveData' {
  declare module.exports: any;
}

declare module 'vue-chartjs/test/unit/specs/Pie.spec' {
  declare module.exports: any;
}

declare module 'vue-chartjs/test/unit/specs/PolarArea.spec' {
  declare module.exports: any;
}

declare module 'vue-chartjs/test/unit/specs/Radar.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-chartjs/build/build.js' {
  declare module.exports: $Exports<'vue-chartjs/build/build'>;
}
declare module 'vue-chartjs/build/dev-client.js' {
  declare module.exports: $Exports<'vue-chartjs/build/dev-client'>;
}
declare module 'vue-chartjs/build/dev-server.js' {
  declare module.exports: $Exports<'vue-chartjs/build/dev-server'>;
}
declare module 'vue-chartjs/build/utils.js' {
  declare module.exports: $Exports<'vue-chartjs/build/utils'>;
}
declare module 'vue-chartjs/build/webpack.base.conf.js' {
  declare module.exports: $Exports<'vue-chartjs/build/webpack.base.conf'>;
}
declare module 'vue-chartjs/build/webpack.dev.conf.js' {
  declare module.exports: $Exports<'vue-chartjs/build/webpack.dev.conf'>;
}
declare module 'vue-chartjs/build/webpack.prod.conf.js' {
  declare module.exports: $Exports<'vue-chartjs/build/webpack.prod.conf'>;
}
declare module 'vue-chartjs/build/webpack.release.js' {
  declare module.exports: $Exports<'vue-chartjs/build/webpack.release'>;
}
declare module 'vue-chartjs/config/dev.env.js' {
  declare module.exports: $Exports<'vue-chartjs/config/dev.env'>;
}
declare module 'vue-chartjs/config/index.js' {
  declare module.exports: $Exports<'vue-chartjs/config/index'>;
}
declare module 'vue-chartjs/config/prod.env.js' {
  declare module.exports: $Exports<'vue-chartjs/config/prod.env'>;
}
declare module 'vue-chartjs/config/test.env.js' {
  declare module.exports: $Exports<'vue-chartjs/config/test.env'>;
}
declare module 'vue-chartjs/dist/vue-chartjs.js' {
  declare module.exports: $Exports<'vue-chartjs/dist/vue-chartjs'>;
}
declare module 'vue-chartjs/docs/dist/vue-chartjs.js' {
  declare module.exports: $Exports<'vue-chartjs/docs/dist/vue-chartjs'>;
}
declare module 'vue-chartjs/src/BaseCharts/Bar.js' {
  declare module.exports: $Exports<'vue-chartjs/src/BaseCharts/Bar'>;
}
declare module 'vue-chartjs/src/BaseCharts/Bubble.js' {
  declare module.exports: $Exports<'vue-chartjs/src/BaseCharts/Bubble'>;
}
declare module 'vue-chartjs/src/BaseCharts/Doughnut.js' {
  declare module.exports: $Exports<'vue-chartjs/src/BaseCharts/Doughnut'>;
}
declare module 'vue-chartjs/src/BaseCharts/Line.js' {
  declare module.exports: $Exports<'vue-chartjs/src/BaseCharts/Line'>;
}
declare module 'vue-chartjs/src/BaseCharts/Pie.js' {
  declare module.exports: $Exports<'vue-chartjs/src/BaseCharts/Pie'>;
}
declare module 'vue-chartjs/src/BaseCharts/PolarArea.js' {
  declare module.exports: $Exports<'vue-chartjs/src/BaseCharts/PolarArea'>;
}
declare module 'vue-chartjs/src/BaseCharts/Radar.js' {
  declare module.exports: $Exports<'vue-chartjs/src/BaseCharts/Radar'>;
}
declare module 'vue-chartjs/src/examples/BarExample.js' {
  declare module.exports: $Exports<'vue-chartjs/src/examples/BarExample'>;
}
declare module 'vue-chartjs/src/examples/BubbleExample.js' {
  declare module.exports: $Exports<'vue-chartjs/src/examples/BubbleExample'>;
}
declare module 'vue-chartjs/src/examples/DoughnutExample.js' {
  declare module.exports: $Exports<'vue-chartjs/src/examples/DoughnutExample'>;
}
declare module 'vue-chartjs/src/examples/LineExample.js' {
  declare module.exports: $Exports<'vue-chartjs/src/examples/LineExample'>;
}
declare module 'vue-chartjs/src/examples/PieExample.js' {
  declare module.exports: $Exports<'vue-chartjs/src/examples/PieExample'>;
}
declare module 'vue-chartjs/src/examples/PolarAreaExample.js' {
  declare module.exports: $Exports<'vue-chartjs/src/examples/PolarAreaExample'>;
}
declare module 'vue-chartjs/src/examples/RadarExample.js' {
  declare module.exports: $Exports<'vue-chartjs/src/examples/RadarExample'>;
}
declare module 'vue-chartjs/src/examples/ReactiveExample.js' {
  declare module.exports: $Exports<'vue-chartjs/src/examples/ReactiveExample'>;
}
declare module 'vue-chartjs/src/examples/ReactivePropExample.js' {
  declare module.exports: $Exports<'vue-chartjs/src/examples/ReactivePropExample'>;
}
declare module 'vue-chartjs/src/helpers/options.js' {
  declare module.exports: $Exports<'vue-chartjs/src/helpers/options'>;
}
declare module 'vue-chartjs/src/index.js' {
  declare module.exports: $Exports<'vue-chartjs/src/index'>;
}
declare module 'vue-chartjs/src/mixins/index.js' {
  declare module.exports: $Exports<'vue-chartjs/src/mixins/index'>;
}
declare module 'vue-chartjs/src/mixins/reactiveData.js' {
  declare module.exports: $Exports<'vue-chartjs/src/mixins/reactiveData'>;
}
declare module 'vue-chartjs/src/mixins/reactiveProp.js' {
  declare module.exports: $Exports<'vue-chartjs/src/mixins/reactiveProp'>;
}
declare module 'vue-chartjs/test/e2e/custom-assertions/elementCount.js' {
  declare module.exports: $Exports<'vue-chartjs/test/e2e/custom-assertions/elementCount'>;
}
declare module 'vue-chartjs/test/e2e/nightwatch.conf.js' {
  declare module.exports: $Exports<'vue-chartjs/test/e2e/nightwatch.conf'>;
}
declare module 'vue-chartjs/test/e2e/runner.js' {
  declare module.exports: $Exports<'vue-chartjs/test/e2e/runner'>;
}
declare module 'vue-chartjs/test/e2e/specs/test.js' {
  declare module.exports: $Exports<'vue-chartjs/test/e2e/specs/test'>;
}
declare module 'vue-chartjs/test/unit/index.js' {
  declare module.exports: $Exports<'vue-chartjs/test/unit/index'>;
}
declare module 'vue-chartjs/test/unit/karma.conf.js' {
  declare module.exports: $Exports<'vue-chartjs/test/unit/karma.conf'>;
}
declare module 'vue-chartjs/test/unit/specs/Bar.spec.js' {
  declare module.exports: $Exports<'vue-chartjs/test/unit/specs/Bar.spec'>;
}
declare module 'vue-chartjs/test/unit/specs/Bubble.spec.js' {
  declare module.exports: $Exports<'vue-chartjs/test/unit/specs/Bubble.spec'>;
}
declare module 'vue-chartjs/test/unit/specs/Doughnut.spec.js' {
  declare module.exports: $Exports<'vue-chartjs/test/unit/specs/Doughnut.spec'>;
}
declare module 'vue-chartjs/test/unit/specs/helpers/options.spec.js' {
  declare module.exports: $Exports<'vue-chartjs/test/unit/specs/helpers/options.spec'>;
}
declare module 'vue-chartjs/test/unit/specs/Line.spec.js' {
  declare module.exports: $Exports<'vue-chartjs/test/unit/specs/Line.spec'>;
}
declare module 'vue-chartjs/test/unit/specs/mixins/reactiveData.js' {
  declare module.exports: $Exports<'vue-chartjs/test/unit/specs/mixins/reactiveData'>;
}
declare module 'vue-chartjs/test/unit/specs/Pie.spec.js' {
  declare module.exports: $Exports<'vue-chartjs/test/unit/specs/Pie.spec'>;
}
declare module 'vue-chartjs/test/unit/specs/PolarArea.spec.js' {
  declare module.exports: $Exports<'vue-chartjs/test/unit/specs/PolarArea.spec'>;
}
declare module 'vue-chartjs/test/unit/specs/Radar.spec.js' {
  declare module.exports: $Exports<'vue-chartjs/test/unit/specs/Radar.spec'>;
}
