// flow-typed signature: 80398b72d20a3ee46a1b1cb291bdc920
// flow-typed version: <<STUB>>/vue-stripe_vjamesearl/vue-stripe/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-stripe'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-stripe' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-stripe/dist/index' {
  declare module.exports: any;
}

declare module 'vue-stripe/src/bus' {
  declare module.exports: any;
}

declare module 'vue-stripe/src/index' {
  declare module.exports: any;
}

declare module 'vue-stripe/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-stripe/dist/index.js' {
  declare module.exports: $Exports<'vue-stripe/dist/index'>;
}
declare module 'vue-stripe/src/bus.js' {
  declare module.exports: $Exports<'vue-stripe/src/bus'>;
}
declare module 'vue-stripe/src/index.js' {
  declare module.exports: $Exports<'vue-stripe/src/index'>;
}
declare module 'vue-stripe/webpack.config.js' {
  declare module.exports: $Exports<'vue-stripe/webpack.config'>;
}
