// flow-typed signature: 1fe9593a7b59293e37e319bb0e5f85c5
// flow-typed version: <<STUB>>/vue2-dropzone_vallentong/vue-dropzone#vue2/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue2-dropzone'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue2-dropzone' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue2-dropzone/build/base' {
  declare module.exports: any;
}

declare module 'vue2-dropzone/build/dev' {
  declare module.exports: any;
}

declare module 'vue2-dropzone/build/prod' {
  declare module.exports: any;
}

declare module 'vue2-dropzone/dev/bundle' {
  declare module.exports: any;
}

declare module 'vue2-dropzone/dev/index' {
  declare module.exports: any;
}

declare module 'vue2-dropzone/dist/vue2-dropzone' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue2-dropzone/build/base.js' {
  declare module.exports: $Exports<'vue2-dropzone/build/base'>;
}
declare module 'vue2-dropzone/build/dev.js' {
  declare module.exports: $Exports<'vue2-dropzone/build/dev'>;
}
declare module 'vue2-dropzone/build/prod.js' {
  declare module.exports: $Exports<'vue2-dropzone/build/prod'>;
}
declare module 'vue2-dropzone/dev/bundle.js' {
  declare module.exports: $Exports<'vue2-dropzone/dev/bundle'>;
}
declare module 'vue2-dropzone/dev/index.js' {
  declare module.exports: $Exports<'vue2-dropzone/dev/index'>;
}
declare module 'vue2-dropzone/dist/vue2-dropzone.js' {
  declare module.exports: $Exports<'vue2-dropzone/dist/vue2-dropzone'>;
}
