const Constants = {
  API_ROOT: 'https://derprecated-inventory-api.azurewebsites.net',

  SET_PROFILE: 'SET_PROFILE',
  GET_PROFILE: 'GET_PROFILE',
  CLEAR_PROFILE: 'CLEAR_PROFILE',

  SET_SESSION: 'SET_SESSION',
  GET_SESSION: 'GET_SESSION',
  CLEAR_SESSION: 'CLEAR_SESSION',

  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT: 'LOGOUT',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',

  REGISTER: 'REGISTER',
  REGISTATION_FAILED: 'REGISTRATION_FAILED',

  GET_PRODUCT: 'GET_PRODUCT',
  SET_PRODUCT: 'SET_PRODUCT',
  CLEAR_PRODUCT: 'CLEAR_PRODUCT',
  CREATE_PRODUCT: 'CREATE_PRODUCT',
  SAVE_PRODUCT: 'SAVE_PRODUCT',

  GET_PRODUCTS: 'GET_PRODUCTS',
  SEARCH_PRODUCTS: 'SEARCH_PRODUCTS',
  UPDATE_PRODUCT_FIELD: 'UPDATE_PRODUCT_FIELD',
  SET_PRODUCT_SEARCH_QUERY: 'SET_PRODUCT_SEARCH_QUERY',
  SET_PRODUCT_SEARCH_RESULTS: 'SET_PRODUCT_SEARCH_RESULTS',
  CLEAR_PRODUCT_SEARCH: 'CLEAR_PRODUCT_SEARCH',
  SET_PRODUCT_LIST: 'SET_PRODUCT_LIST',

  SAVE_USER: 'SAVE_USER',
  SET_USER: 'SET_USER',
  GET_USER: 'GET_USER',
  CLEAR_USER: 'CLEAR_USER',

  GET_USERS: 'GET_USERS',
  SET_USERS: 'SET_USERS',
  SET_USERS_SEARCH_QUERY: 'SET_USERS_SEARCH_QUERY',
  SET_USERS_SEARCH_RESULTS: 'SET_USERS_SEARCH_RESULTS',
  CLEAR_USERS_SEARCH: 'CLEAR_USERS_SEARCH',
};

export default Constants;
