import config from '../config';

export default {
  API_ROOT: process.env.NODE_ENV === 'production' ? config.build.api : config.dev.api,

  SHOW_TOASTR: 'SHOW_TOASTR',

  SET_PROFILE: 'SET_PROFILE',
  GET_PROFILE: 'GET_PROFILE',
  CLEAR_PROFILE: 'CLEAR_PROFILE',

  SET_SESSION: 'SET_SESSION',
  GET_SESSION: 'GET_SESSION',
  CLEAR_SESSION: 'CLEAR_SESSION',

  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT: 'LOGOUT',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  RESET_PASSWORD: 'RESET_PASSWORD',

  REGISTER: 'REGISTER',
  REGISTATION_FAILED: 'REGISTRATION_FAILED',

  GET_PRODUCT: 'GET_PRODUCT',
  SET_PRODUCT: 'SET_PRODUCT',
  CLEAR_PRODUCT: 'CLEAR_PRODUCT',
  CREATE_PRODUCT: 'CREATE_PRODUCT',
  SAVE_PRODUCT: 'SAVE_PRODUCT',
  UPDATED_PRODUCT: 'UPDATED_PRODUCT',

  GET_PRODUCTS: 'GET_PRODUCTS',
  UPDATE_PRODUCT_FIELD: 'UPDATE_PRODUCT_FIELD',
  SET_PRODUCT_SEARCH_QUERY: 'SET_PRODUCT_SEARCH_QUERY',
  SET_PRODUCT_SEARCH_RESULTS: 'SET_PRODUCT_SEARCH_RESULTS',
  CLEAR_PRODUCT_SEARCH: 'CLEAR_PRODUCT_SEARCH',
  SEARCH_PRODUCTS_WITH_TYPEAHEAD: 'SEARCH_PRODUCTS_WITH_TYPEAHEAD',
  DELETE_PRODUCT: 'DELETE_PRODUCT',

  DELETE_PRODUCT_IMAGE: 'DELETE_PRODUCT_IMAGE',

  SAVE_USER: 'SAVE_USER',
  SET_USER: 'SET_USER',
  GET_USER: 'GET_USER',
  CLEAR_USER: 'CLEAR_USER',
  CREATE_USER: 'CREATE_USER',
  GET_USERS: 'GET_USERS',
  SET_USERS: 'SET_USERS',
  SET_USERS_SEARCH_QUERY: 'SET_USERS_SEARCH_QUERY',
  SET_USERS_SEARCH_RESULTS: 'SET_USERS_SEARCH_RESULTS',
  CLEAR_USERS_SEARCH: 'CLEAR_USERS_SEARCH',
  SEARCH_USERS_WITH_TYPEAHEAD: 'SEARCH_USERS_WITH_TYPEAHEAD',

  GET_VENDOR: 'GET_VENDOR',
  GET_VENDORS: 'GET_VENDORS',
  CREATE_VENDOR: 'CREATE_VENDOR',
  SAVE_VENDOR: 'SAVE_VENDOR',
  COUNT_VENDORS: 'COUNT_VENDORS',
  SEARCH_VENDORS_WITH_TYPEAHEAD: 'SEARCH_VENDORS_WITH_TYPEAHEAD',
  SET_VENDOR: 'SET_VENDOR',
  SET_VENDOR_SEARCH_QUERY: 'SET_VENDOR_SEARCH_QUERY',
  SET_VENDOR_SEARCH_RESULTS: 'SET_VENDOR_SEARCH_RESULTS',
  SET_VENDORS: 'SET_VENDORS',
  SET_VENDOR_COUNT: 'SET_VENDOR_COUNT',

  GET_CATEGORY: 'GET_CATEGORY',
  GET_CATEGORIES: 'GET_CATEGORIES',
  CREATE_CATEGORY: 'CREATE_CATEGORY',
  SAVE_CATEGORY: 'SAVE_CATEGORY',
  SET_CATEGORY: 'SET_CATEGORY',
  SET_CATEGORY_SEARCH_QUERY: 'SET_CATEGORY_SEARCH_QUERY',
  SET_CATEGORY_SEARCH_RESULTS: 'SET_CATEGORY_SEARCH_RESULTS',
  SET_CATEGORIES: 'SET_CATEGORIES',
  SET_CATEGORY_COUNT: 'SET_CATEGORY_COUNT',
  COUNT_CATEGORIES: 'COUNT_CATEGORIES',
  SEARCH_CATEGORIES_WITH_TYPEAHEAD: 'SEARCH_CATEGORIES_WITH_TYPEAHEAD',

  GET_WAREHOUSE: 'GET_WAREHOUSE',
  GET_WAREHOUSES: 'GET_WAREHOUSES',
  CREATE_WAREHOUSE: 'CREATE_WAREHOUSE',
  SAVE_WAREHOUSE: 'SAVE_WAREHOUSE',
  COUNT_WAREHOUSES: 'COUNT_WAREHOUSES',
  SEARCH_WAREHOUSES_WITH_TYPEAHEAD: 'SEARCH_WAREHOUSES_WITH_TYPEAHEAD',
  SET_WAREHOUSE: 'SET_WAREHOUSE',
  SET_WAREHOUSE_SEARCH_QUERY: 'SET_WAREHOUSE_SEARCH_QUERY',
  SET_WAREHOUSE_SEARCH_RESULTS: 'SET_WAREHOUSE_SEARCH_RESULTS',
  SET_WAREHOUSES: 'SET_WAREHOUSES',
  SET_WAREHOUSE_COUNT: 'SET_WAREHOUSE_COUNT',

  GET_LOCATION: 'GET_LOCATION',
  GET_LOCATIONS: 'GET_LOCATIONS',
  CREATE_LOCATION: 'CREATE_LOCATION',
  SAVE_LOCATION: 'SAVE_LOCATION',
  COUNT_LOCATIONS: 'COUNT_LOCATIONS',
  DELETE_LOCATION: 'DELETE_LOCATION',
  SEARCH_LOCATIONS_WITH_TYPEAHEAD: 'SEARCH_LOCATIONS_WITH_TYPEAHEAD',
  SET_LOCATION: 'SET_LOCATION',
  SET_LOCATIONS: 'SET_LOCATIONS',
  SET_LOCATION_COUNT: 'SET_LOCATION_COUNT',
  SET_LOCATION_SEARCH_RESULTS: 'SET_LOCATION_SEARCH_RESULTS',

  SET_USER_PERMISSIONS: 'SET_PERMISSIONS',
  SET_USER_PERMISSION: 'SET_PERMISSION',
  UNSET_USER_PERMISSIONS: 'UNSET_PERMISSIONS',
  UNSET_USER_PERMISSION: 'UNSET_PERMISSION',
  GET_PERMISSIONS: 'GET_PERMISSIONS',

  SET_QUANTITY_ON_HAND: 'SET_QUANTITY_ON_HAND',
  GET_QUANTITY_ON_HAND: 'GET_QUANTITY_ON_HAND',
  RECEIVE_INVENTORY: 'RECEIVE_INVENTORY',
  LOCATE_INVENTORY: 'LOCATE_INVENTORY',
  DISPATCH_INVENTORY: 'DISPATCH_INVENTORY',
  GET_INVENTORY_TRANSACTION_LOGS: 'GET_INVENTORY_TRANSACTION_LOGS',
  SET_INVENTORY_TRANSACTION_LOGS: 'SET_INVENTORY_TRANSACTION_LOGS',
  SEARCH_INVENTORY_TRANSACTION_LOGS: 'SEARCH_INVENTORY_TRANSACTION_LOGS',
  COUNT_INVENTORY_LOGS: 'COUNT_INVENTORY_LOGS',
  SET_INVENTORY_TRANSACTION_LOG_COUNT: 'SET_INVENTORY_TRANSACTION_LOG_COUNT',

  GET_SALE: 'GET_SALE',
  GET_SALES: 'GET_SALES',
  SET_SALE: 'SET_SALE',
  GET_DASHBOARD: 'GET_DASHBOARD',
  CREATE_SALE: 'CREATE_SALE',
  SEARCH_SALES_WITH_TYPEAHEAD: 'SEARCH_SALES_WITH_TYPEAHEAD',
  CLEAR_SALE_SEARCH: 'CLEAR_SALE_SEARCH',
  COUNT_SALES: 'COUNT_SALES',
  SET_SALE_COUNT: 'SET_SALE_COUNT',
  SET_SALE_SEARCH_RESULTS: 'SET_SALE_SEARCH_RESULTS',
  SET_DASHBOARD_REPORT: 'SET_DASHBOARD_REPORT',


  GET_SALES_BY_PRODUCT: 'GET_SALES_BY_PRODUCT',
  SET_SALES_BY_PRODUCT: 'SET_SALES_BY_PRODUCT',
  GET_SALES_BY_TOTAL: 'GET_SALES_BY_TOTAL',
  SET_SALES_BY_TOTAL: 'SET_SALES_BY_TOTAL',
  GET_SALES_BY_VENDOR: 'GET_SALES_BY_VENDOR',
  SET_SALES_BY_VENDOR: 'SET_SALES_BY_VENDOR',

  permissions: {
    EVERYTHING: {
      key: 'everything',
      description: 'Everything',
    },
    LOGIN: {
      key: 'login',
      description: 'Can login'
    },
    MANAGE_INVENTORY: {
      key: 'manageInventory',
      description: 'Manage Inventory',
    },
    MANAGE_LOCATIONS: {
      key: 'manageLocations',
      description: 'Manage Locations',
    },
    MANAGE_PRODUCTS: {
      key: 'manageProducts',
      description: 'Manage Products',
    },
    MANAGE_USERS: {
      key: 'manageUsers',
      description: 'Manage Users',
    },
    MANAGE_VENDORS: {
      key: 'manageVendors',
      description: 'Manage Vendors',
    },
    MANAGE_WAREHOUSES: {
      key: 'manageWarehouses',
      description: 'Manage Warehouses',
    },
    MANAGE_CATEGORIES: {
      key: 'manageCategories',
      description: 'Manage Categories',
    },

    READ_LOCATIONS: {
      key: 'readLocations',
      description: 'Read Locations',
    },
    READ_PRODUCTS: {
      key: 'readProducts',
      description: 'Read Products',
    },
    READ_REPORTS: {
      key: 'readReports',
      description: 'Read Reports',
    },
    READ_USERS: {
      key: 'readUsers',
      description: 'Read Users',
    },
    READ_VENDORS: {
      key: 'readVendors',
      description: 'Read Vendors',
    },
    READ_WAREHOUSES: {
      key: 'readWarehouses',
      description: 'Read Warehouses',
    },
    READ_CATEGORIES: {
      key: 'readCategories',
      description: 'Read Categories',
    },

    UPSERT_LOCATIONS: {
      key: 'upsertLocations',
      description: 'Upsert Locations',
    },
    UPSERT_PRODUCTS: {
      key: 'upsertProducts',
      description: 'Upsert Products',
    },
    UPSERT_USERS: {
      key: 'upsertUsers',
      description: 'Upsert Users',
    },
    UPSERT_VENDORS: {
      key: 'upsertVendors',
      description: 'Upsert Vendors',
    },
    UPSERT_WAREHOUSES: {
      key: 'upsertWarehouses',
      description: 'Upsert Warehouses',
    },
    UPSERT_CATEGORIES: {
      key: 'upsertCategories',
      description: 'Upsert Categories',
    },

    DELETE_LOCATIONS: {
      key: 'deleteLocations',
      description: 'Delete Locations',
    },
    DELETE_PRODUCTS: {
      key: 'deleteProducts',
      description: 'Delete Products',
    },
    DELETE_USERS: {
      key: 'deleteUsers',
      description: 'Delete Users',
    },
    DELETE_VENDORS: {
      key: 'deleteVendors',
      description: 'Delete Vendors',
    },
    DELETE_WAREHOUSES: {
      key: 'deleteWarehouses',
      description: 'Delete Warehouses',
    },
    DELETE_CATEGORIES: {
      key: 'deleteCategories',
      description: 'Delete Categories',
    },

    RECEIVE_INVENTORY: {
      key: 'receiveInventory',
      description: 'Receive Inventory',
    },
    RELEASE_INVENTORY: {
      key: 'releaseInventory',
      description: 'Release Inventory',
    },
    DISPATCH_INVENTORY: {
      key: 'dispatchInventory',
      description: 'Dispatch Inventory',
    }
  }
};
